description: Read or bump the package version in the Cabal-file
name: Edit version in Cabal-file
author: Nikita Volkov
inputs:
  work-dir:
    description: Directory in which the Cabal-file is located
    required: false
    default: .
  mode:
    description: |
      One of the following: "get", "set", "bump".
      "read" is also allowed but deprecated, it acts the same as "get".
    required: true
  bump-place:
    description: Index of the bumped version place, when the mode is "bump"
    required: false
  set-value:
    description: Version to be written, when the mode is "set"
    required: false
outputs:
  before:
    description: Version before edit
  after:
    description: Version after edit
runs:
  using: docker
  image: docker://ghcr.io/nikita-volkov/edit-cabal-version.github-action:v1.0.0
  env:
    work-dir: ${{ inputs.work-dir }}
    mode: ${{ inputs.mode }}
    bump-place: ${{ inputs.bump-place }}
    set-value: ${{ inputs.set-value }}
