name: Read or bump the version in a Cabal file
inputs:
  work-dir:
    type: string
    description: Directory in which the Cabal-file is located
    required: false
    default: .
  mode:
    type: string
    required: true
    description: read | bump
  bump-place:
    type: int
    required: false
    description: If the mode is bump, then the index of the bumped version place
outputs:
  before:
    description: Version before edit
  after:
    description: Version after edit
runs:
  using: docker
  image: docker://ghcr.io/nikita-volkov/edit-cabal-version.github-action:v1.0.0
  args:
    - ${{ inputs.work-dir }}
    - ${{ inputs.mode }}
    - ${{ inputs.bump-place }}
