
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.stack
            app/.stack-work
          key: ${{ runner.os }}-${{ hashFiles('stack.yaml.lock') }}-${{ hashFiles('**.cabal') }}
          restore-keys: |
            ${{ runner.os }}-${{ hashFiles('stack.yaml.lock') }}-${{ hashFiles('**.cabal') }}
            ${{ runner.os }}-${{ hashFiles('stack.yaml.lock') }}-
            ${{ runner.os }}-
      - run: |
          cd app
          stack build --local-bin-path ../dist --copy-bins
